### PR TITLE
Added Bengali Language

### PR DESCRIPTION
**Pull request by lovebdsobuj**

### CODE REVIEW

**Review by lances101 — APPROVED** [review]
Minor changes. Nothing to really review. Approved.

**Comment by lances101** [comment]
Sorry for being so late. I will update the plugin today/tomorrow.

**Comment by lovebdsobuj** [comment]
Change **ActionKeyword** `tr` to `gt` it will be good also another plugin have save **ActionKeyword** `tr`

**Comment by lances101** [comment]
**ActionKeyword**s are configurable, I don't see enough reasons in changing the default at this point. What plugin are you talking about? Is it a default plugin included with Wox?

**Comment by lovebdsobuj** [comment]
I understand, but _gt_ will be perfect ActionKeyword, because its short form your plugin name _Google Translate_ and easy to understand.
Also is there another _Translator_ plugin have same ActionKeyword _tr_. 
http://www.getwox.com/plugin/38
_Its not default plugin included with Wox._

> I don't see enough reasons in changing the default at this point.

If user install two plugin that have same _ActionKeyword_, which plugin would work?

**Comment by lances101** [comment]
This plugin is a continuation of `Wox.Plugin.Translate` since armaldio
discontinued the project and the Wox Plugin Management thing doesn't really
have a way of delegating access of plugins between different users.

**Comment by lances101** [comment]
Regarding default keywords, both plugins would answer the query. Again, every user can personally change the ActionKeyword to whatever he wants to through the settings GUI. I really fail to see a problem there.

**Comment by lovebdsobuj** [comment]
If is there no problem having same ActionKeyword different two plugin
then it's okay.

**Pull request merged**
